SELECT 
    b.ID,
    b.GENOTYPE,
    a.GENOTYPE AS PARENT_GENOTYPE
FROM
    ECOLI_DATA AS a
    LEFT OUTER JOIN ECOLI_DATA AS b
    ON a.ID = b.PARENT_ID
    WHERE a.GENOTYPE & b.GENOTYPE = a.GENOTYPE
ORDER BY
    b.ID ASC;