SELECT
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    (F.MAX - E.SIZE_OF_COLONY) AS YEAR_DEV,
    E.ID
FROM
    ECOLI_DATA AS E
JOIN (
    SELECT
        YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
        MAX(E.SIZE_OF_COLONY) AS MAX
    FROM
        ECOLI_DATA AS E
        GROUP BY YEAR
    ) AS F
    ON YEAR(E.DIFFERENTIATION_DATE) = F.YEAR
ORDER BY 
    YEAR, YEAR_DEV ASC;